# ANN

In [4]:
import numpy as np

In [7]:


CM_ANN = np.array([[[25103,   408],
                              [  439,  6114]],
                             [[31305,   110],
                              [   61,   588]],
                             [[31878,    34],
                              [   22,   130]],
                             [[30603,   322],
                              [  190,   949]],
                             [[31226,    81],
                              [   73,   684]],
                             [[29658,   354],
                              [  137,  1915]],
                             [[23199,   481],
                              [  447,  7937]],
                             [[31453,    69],
                              [   24,   518]],
                             [[26474,   447],
                              [  288,  4855]],
                             [[31878,    46],
                              [   14,   126]],
                             [[30966,   149],
                              [  128,   821]],
                             [[30677,   142],
                              [  129,  1116]],
                             [[30244,   166],
                              [   71,  1583]],
                             [[28805,   554],
                              [  373,  2332]]])

# get the number of classes
num_classes = CM_ANN.shape[0]

# initialize arrays to store TP, FP, TN, FN values for each class
TP = np.zeros(num_classes)
FP = np.zeros(num_classes)
TN = np.zeros(num_classes)
FN = np.zeros(num_classes)

# iterate over each class and calculate TP, FP, TN, FN
for i in range(num_classes):
    TP[i] = CM_ANN[i][0][0]
    FP[i] = CM_ANN[i][1][0]
    FN[i] = CM_ANN[i][0][1]
    TN[i] = CM_ANN[i][1][1]

print("True Positive (TP) values for each class:", TP)
print("False Positive (FP) values for each class:", FP)
print("True Negative (TN) values for each class:", TN)
print("False Negative (FN) values for each class:", FN)

True Positive (TP) values for each class: [25103. 31305. 31878. 30603. 31226. 29658. 23199. 31453. 26474. 31878.
 30966. 30677. 30244. 28805.]
False Positive (FP) values for each class: [439.  61.  22. 190.  73. 137. 447.  24. 288.  14. 128. 129.  71. 373.]
True Negative (TN) values for each class: [6114.  588.  130.  949.  684. 1915. 7937.  518. 4855.  126.  821. 1116.
 1583. 2332.]
False Negative (FN) values for each class: [408. 110.  34. 322.  81. 354. 481.  69. 447.  46. 149. 142. 166. 554.]

# Decision Tree

In [9]:
CM_DT = np.array([[[25145,   366],
        [  390,  6163]],

       [[31359,    56],
        [   60,   589]],

       [[31902,    10],
        [   26,   126]],

       [[30745,   180],
        [  188,   951]],

       [[31245,    62],
        [   62,   695]],

       [[29854,   158],
        [  120,  1932]],

       [[23292,   388],
        [  368,  8016]],

       [[31484,    38],
        [   26,   516]],

       [[26675,   246],
        [  286,  4857]],

       [[31896,    28],
        [   18,   122]],

       [[30997,   118],
        [   80,   869]],

       [[30727,    92],
        [  132,  1113]],

       [[30332,    78],
        [   88,  1566]],

       [[28983,   376],
        [  352,  2353]]])

# get the number of classes
num_classes = CM_DT.shape[0]

# initialize arrays to store TP, FP, TN, FN values for each class
TP = np.zeros(num_classes)
FP = np.zeros(num_classes)
TN = np.zeros(num_classes)
FN = np.zeros(num_classes)

# iterate over each class and calculate TP, FP, TN, FN
for i in range(num_classes):
    TP[i] = CM_DT[i][0][0]
    FP[i] = CM_DT[i][1][0]
    FN[i] = CM_DT[i][0][1]
    TN[i] = CM_DT[i][1][1]

print("True Positive (TP) values for each class:", TP)
print("False Positive (FP) values for each class:", FP)
print("True Negative (TN) values for each class:", TN)
print("False Negative (FN) values for each class:", FN)

True Positive (TP) values for each class: [25145. 31359. 31902. 30745. 31245. 29854. 23292. 31484. 26675. 31896.
 30997. 30727. 30332. 28983.]
False Positive (FP) values for each class: [390.  60.  26. 188.  62. 120. 368.  26. 286.  18.  80. 132.  88. 352.]
True Negative (TN) values for each class: [6163.  589.  126.  951.  695. 1932. 8016.  516. 4857.  122.  869. 1113.
 1566. 2353.]
False Negative (FN) values for each class: [366.  56.  10. 180.  62. 158. 388.  38. 246.  28. 118.  92.  78. 376.]


# Random Forest

In [10]:
CM_RF = np.array([[[25347,   164],
        [  417,  6136]],

       [[31408,     7],
        [   86,   563]],

       [[31912,     0],
        [   24,   128]],

       [[30913,    12],
        [  288,   851]],

       [[31291,    16],
        [   90,   667]],

       [[29934,    78],
        [  137,  1915]],

       [[23538,   142],
        [  423,  7961]],

       [[31514,     8],
        [   34,   508]],

       [[26846,    75],
        [  326,  4817]],

       [[31918,     6],
        [   26,   114]],

       [[31092,    23],
        [  134,   815]],

       [[30801,    18],
        [  175,  1070]],

       [[30378,    32],
        [   72,  1582]],

       [[29279,    80],
        [  492,  2213]]])

# get the number of classes
num_classes = CM_RF.shape[0]

# initialize arrays to store TP, FP, TN, FN values for each class
TP = np.zeros(num_classes)
FP = np.zeros(num_classes)
TN = np.zeros(num_classes)
FN = np.zeros(num_classes)

# iterate over each class and calculate TP, FP, TN, FN
for i in range(num_classes):
    TP[i] = CM_RF[i][0][0]
    FP[i] = CM_RF[i][1][0]
    FN[i] = CM_RF[i][0][1]
    TN[i] = CM_RF[i][1][1]

print("True Positive (TP) values for each class:", TP)
print("False Positive (FP) values for each class:", FP)
print("True Negative (TN) values for each class:", TN)
print("False Negative (FN) values for each class:", FN)

True Positive (TP) values for each class: [25347. 31408. 31912. 30913. 31291. 29934. 23538. 31514. 26846. 31918.
 31092. 30801. 30378. 29279.]
False Positive (FP) values for each class: [417.  86.  24. 288.  90. 137. 423.  34. 326.  26. 134. 175.  72. 492.]
True Negative (TN) values for each class: [6136.  563.  128.  851.  667. 1915. 7961.  508. 4817.  114.  815. 1070.
 1582. 2213.]
False Negative (FN) values for each class: [164.   7.   0.  12.  16.  78. 142.   8.  75.   6.  23.  18.  32.  80.]

# Naive Bayes

In [15]:
CM_NB = np.array([[[22743,  2768],
        [ 4244,  2309]],

       [[31036,   379],
        [  537,   112]],

       [[31296,   616],
        [   88,    64]],

       [[30763,   162],
        [ 1111,    28]],

       [[31032,   275],
        [  371,   386]],

       [[25591,  4421],
        [  201,  1851]],

       [[20809,  2871],
        [ 2967,  5417]],

       [[30149,  1373],
        [   65,   477]],

       [[25617,  1304],
        [ 3227,  1916]],

       [[31768,   156],
        [  115,    25]],

       [[30122,   993],
        [  920,    29]],

       [[29445,  1374],
        [  975,   270]],

       [[30109,   301],
        [ 1075,   579]],

       [[28097,  1262],
        [ 2359,   346]]])

# get the number of classes
num_classes = CM_NB.shape[0]

# initialize arrays to store TP, FP, TN, FN values for each class
TP = np.zeros(num_classes)
FP = np.zeros(num_classes)
TN = np.zeros(num_classes)
FN = np.zeros(num_classes)

# iterate over each class and calculate TP, FP, TN, FN
for i in range(num_classes):
    TP[i] = CM_NB[i][0][0]
    FP[i] = CM_NB[i][1][0]
    FN[i] = CM_NB[i][0][1]
    TN[i] = CM_NB[i][1][1]

print("True Positive (TP) values for each class:", TP)
print("False Positive (FP) values for each class:", FP)
print("True Negative (TN) values for each class:", TN)
print("False Negative (FN) values for each class:", FN)

True Positive (TP) values for each class: [22743. 31036. 31296. 30763. 31032. 25591. 20809. 30149. 25617. 31768.
 30122. 29445. 30109. 28097.]
False Positive (FP) values for each class: [4244.  537.   88. 1111.  371.  201. 2967.   65. 3227.  115.  920.  975.
 1075. 2359.]
True Negative (TN) values for each class: [2309.  112.   64.   28.  386. 1851. 5417.  477. 1916.   25.   29.  270.
  579.  346.]
False Negative (FN) values for each class: [2768.  379.  616.  162.  275. 4421. 2871. 1373. 1304.  156.  993. 1374.
  301. 1262.]

# Logistic Regression

In [16]:
CM_LR = np.array([[[21648,  3863],
        [ 1522,  5031]],

       [[31339,    76],
        [  513,   136]],

       [[31903,     9],
        [  122,    30]],

       [[30869,    56],
        [ 1103,    36]],

       [[31165,   142],
        [  410,   347]],

       [[29045,   967],
        [  430,  1622]],

       [[20172,  3508],
        [ 1597,  6787]],

       [[31408,   114],
        [  210,   332]],

       [[25124,  1797],
        [ 1960,  3183]],

       [[31913,    11],
        [  109,    31]],

       [[30994,   121],
        [  553,   396]],

       [[30606,   213],
        [  828,   417]],

       [[29937,   473],
        [  304,  1350]],

       [[28750,   609],
        [ 2298,   407]]])

# get the number of classes
num_classes = CM_LR.shape[0]

# initialize arrays to store TP, FP, TN, FN values for each class
TP = np.zeros(num_classes)
FP = np.zeros(num_classes)
TN = np.zeros(num_classes)
FN = np.zeros(num_classes)

# iterate over each class and calculate TP, FP, TN, FN
for i in range(num_classes):
    TP[i] = CM_LR[i][0][0]
    FP[i] = CM_LR[i][1][0]
    FN[i] = CM_LR[i][0][1]
    TN[i] = CM_LR[i][1][1]

print("True Positive (TP) values for each class:", TP)
print("False Positive (FP) values for each class:", FP)
print("True Negative (TN) values for each class:", TN)
print("False Negative (FN) values for each class:", FN)

True Positive (TP) values for each class: [21648. 31339. 31903. 30869. 31165. 29045. 20172. 31408. 25124. 31913.
 30994. 30606. 29937. 28750.]
False Positive (FP) values for each class: [1522.  513.  122. 1103.  410.  430. 1597.  210. 1960.  109.  553.  828.
  304. 2298.]
True Negative (TN) values for each class: [5031.  136.   30.   36.  347. 1622. 6787.  332. 3183.   31.  396.  417.
 1350.  407.]
False Negative (FN) values for each class: [3863.   76.    9.   56.  142.  967. 3508.  114. 1797.   11.  121.  213.
  473.  609.]

# KNN

In [18]:
CM_KNN = np.array([[[24919,   592],
        [ 3420,  3133]],

       [[31406,     9],
        [  586,    63]],

       [[31912,     0],
        [  152,     0]],

       [[30925,     0],
        [ 1139,     0]],

       [[31271,    36],
        [  615,   142]],

       [[29834,   178],
        [ 1052,  1000]],

       [[22977,   703],
        [ 2827,  5557]],

       [[31392,   130],
        [  263,   279]],

       [[26567,   354],
        [ 2432,  2711]],

       [[31924,     0],
        [  140,     0]],

       [[31063,    52],
        [  638,   311]],

       [[30795,    24],
        [ 1097,   148]],

       [[30217,   193],
        [  643,  1011]],

       [[29300,    59],
        [ 2405,   300]]])

# get the number of classes
num_classes = CM_RF.shape[0]

# initialize arrays to store TP, FP, TN, FN values for each class
TP = np.zeros(num_classes)
FP = np.zeros(num_classes)
TN = np.zeros(num_classes)
FN = np.zeros(num_classes)

# iterate over each class and calculate TP, FP, TN, FN
for i in range(num_classes):
    TP[i] = CM_KNN[i][0][0]
    FP[i] = CM_KNN[i][1][0]
    FN[i] = CM_KNN[i][0][1]
    TN[i] = CM_KNN[i][1][1]

print("True Positive (TP) values for each class:", TP)
print("False Positive (FP) values for each class:", FP)
print("True Negative (TN) values for each class:", TN)
print("False Negative (FN) values for each class:", FN)

True Positive (TP) values for each class: [24919. 31406. 31912. 30925. 31271. 29834. 22977. 31392. 26567. 31924.
 31063. 30795. 30217. 29300.]
False Positive (FP) values for each class: [3420.  586.  152. 1139.  615. 1052. 2827.  263. 2432.  140.  638. 1097.
  643. 2405.]
True Negative (TN) values for each class: [3133.   63.    0.    0.  142. 1000. 5557.  279. 2711.    0.  311.  148.
 1011.  300.]
False Negative (FN) values for each class: [592.   9.   0.   0.  36. 178. 703. 130. 354.   0.  52.  24. 193.  59.]

# SVM

In [19]:
CM_SVM = np.array([[[25347,   164],
        [  417,  6136]],

       [[31408,     7],
        [   86,   563]],

       [[31912,     0],
        [   24,   128]],

       [[30913,    12],
        [  288,   851]],

       [[31291,    16],
        [   90,   667]],

       [[29934,    78],
        [  137,  1915]],

       [[23538,   142],
        [  423,  7961]],

       [[31514,     8],
        [   34,   508]],

       [[26846,    75],
        [  326,  4817]],

       [[31918,     6],
        [   26,   114]],

       [[31092,    23],
        [  134,   815]],

       [[30801,    18],
        [  175,  1070]],

       [[30378,    32],
        [   72,  1582]],

       [[29279,    80],
        [  492,  2213]]])

# get the number of classes
num_classes = CM_SVM.shape[0]

# initialize arrays to store TP, FP, TN, FN values for each class
TP = np.zeros(num_classes)
FP = np.zeros(num_classes)
TN = np.zeros(num_classes)
FN = np.zeros(num_classes)

# iterate over each class and calculate TP, FP, TN, FN
for i in range(num_classes):
    TP[i] = CM_SVM[i][0][0]
    FP[i] = CM_SVM[i][1][0]
    FN[i] = CM_SVM[i][0][1]
    TN[i] = CM_SVM[i][1][1]

print("True Positive (TP) values for each class:", TP)
print("False Positive (FP) values for each class:", FP)
print("True Negative (TN) values for each class:", TN)
print("False Negative (FN) values for each class:", FN)

True Positive (TP) values for each class: [25347. 31408. 31912. 30913. 31291. 29934. 23538. 31514. 26846. 31918.
 31092. 30801. 30378. 29279.]
False Positive (FP) values for each class: [417.  86.  24. 288.  90. 137. 423.  34. 326.  26. 134. 175.  72. 492.]
True Negative (TN) values for each class: [6136.  563.  128.  851.  667. 1915. 7961.  508. 4817.  114.  815. 1070.
 1582. 2213.]
False Negative (FN) values for each class: [164.   7.   0.  12.  16.  78. 142.   8.  75.   6.  23.  18.  32.  80.]